/**
 * 练习项 → pinyin-voice 文件名（默认一声，与库内命名 {音节}{声调}.mp3 一致）。
 * 声母用呼读音音节；韵母/整体认读尽量用对应完整音节。
 */
export const TOKEN_TO_VOICE_FILE: Record<string, string> = {
  // 声母（呼读音）
  b: 'bo1.mp3',
  p: 'po1.mp3',
  m: 'mo1.mp3',
  f: 'fo1.mp3',
  d: 'de1.mp3',
  t: 'te1.mp3',
  n: 'ne1.mp3',
  l: 'le1.mp3',
  g: 'ge1.mp3',
  k: 'ke1.mp3',
  h: 'he1.mp3',
  j: 'ji1.mp3',
  q: 'qi1.mp3',
  x: 'xi1.mp3',
  zh: 'zhi1.mp3',
  ch: 'chi1.mp3',
  sh: 'shi1.mp3',
  r: 'ri1.mp3',
  z: 'zi1.mp3',
  c: 'ci1.mp3',
  s: 'si1.mp3',
  y: 'yi1.mp3',
  w: 'wu1.mp3',

  // 韵母
  a: 'a1.mp3',
  o: 'o1.mp3',
  e: 'e1.mp3',
  i: 'yi1.mp3',
  u: 'wu1.mp3',
  ü: 'yu1.mp3',
  ai: 'ai1.mp3',
  ei: 'ei1.mp3',
  ui: 'wei1.mp3',
  ao: 'ao1.mp3',
  ou: 'ou1.mp3',
  iu: 'you1.mp3',
  ie: 'ye1.mp3',
  üe: 'yue1.mp3',
  er: 'er1.mp3',
  an: 'an1.mp3',
  en: 'en1.mp3',
  in: 'yin1.mp3',
  un: 'wen1.mp3',
  ün: 'yun1.mp3',
  ang: 'ang1.mp3',
  eng: 'eng1.mp3',
  ing: 'ying1.mp3',
  ong: 'hong1.mp3',
  iao: 'jiao1.mp3',
  ian: 'bian1.mp3',
  iang: 'liang1.mp3',
  iong: 'xiong1.mp3',
  uai: 'shuai1.mp3',
  uan: 'tuan1.mp3',
  uang: 'huang1.mp3',

  // 整体认读
  zhi: 'zhi1.mp3',
  chi: 'chi1.mp3',
  shi: 'shi1.mp3',
  ri: 'ri1.mp3',
  zi: 'zi1.mp3',
  ci: 'ci1.mp3',
  si: 'si1.mp3',
  yi: 'yi1.mp3',
  wu: 'wu1.mp3',
  yu: 'yu1.mp3',
  ye: 'ye1.mp3',
  yue: 'yue1.mp3',
  yuan: 'yuan1.mp3',
  yin: 'yin1.mp3',
  yun: 'yun1.mp3',
  ying: 'ying1.mp3',
}

export function tokenToVoiceFilename(token: string): string | null {
  return TOKEN_TO_VOICE_FILE[token] ?? null
}
